CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    task VARCHAR(255) NOT NULL,
    is_done BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS users (
 ID SERIAL PRIMARY KEY,
 Email VARCHAR(50) NOT NULL,
 Users_Password VARCHAR(255) NOT NULL,
 CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
 UpdatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
 DeletedAt TIMESTAMP DEFAULT NULL
)